### ISSUE TITLE
compiling error in linuxmint

### ISSUE THREAD

**Issue by ramdroid2015** [Groestlcoin/vanitygen#6]
I have compiling error in linuxmint:

`
cc -ggdb -O3 -Wall   -c -o vanitygen.o vanitygen.c
In file included from vanitygen.c:32:
pattern.h:54:12: error: field ‘vxc_bntarg’ has incomplete type
   54 |  BIGNUM    vxc_bntarg;
      |            ^~~~~~~~~~
pattern.h:55:12: error: field ‘vxc_bnbase’ has incomplete type
   55 |  BIGNUM    vxc_bnbase;
      |            ^~~~~~~~~~
pattern.h:56:12: error: field ‘vxc_bntmp’ has incomplete type
   56 |  BIGNUM    vxc_bntmp;
      |            ^~~~~~~~~
pattern.h:57:12: error: field ‘vxc_bntmp2’ has incomplete type
   57 |  BIGNUM    vxc_bntmp2;
      |            ^~~~~~~~~~
vanitygen.c: In function ‘vg_thread_loop’:
vanitygen.c:134:21: error: ‘BN_MASK2’ undeclared (first use in this function)
  134 |    if ((rekey_at == BN_MASK2) || (rekey_at > rekey_max))
      |                     ^~~~~~~~
vanitygen.c:134:21: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: vanitygen.o] Error 1
`

**Comment by gruve-p** [comment]
What OpenSSL version do you have installed?

**Comment by ramdroid2015** [comment]
> What OpenSSL version do you have installed?

OpenSSL 1.1.1f  31 Mar 2020

**Comment by gruve-p** [comment]
Can you compile latest master? We do not use `BN_MASK2`

**Comment by gruve-p** [comment]
no response from OP so closing
